name: upper-build

on:
    push:
        paths:
            - ".github/workflow/upper-build.yml"
            - "upper/**"
    workflow_dispatch: # manual

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - run: go version
